- hosts: localhost
  connection: local
  gather_facts: no
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: no

    - name: password
      prompt: What is your password?
      
    - name: RGName
      prompt: What is your username?
      private: no
      
  tasks:
  - name: Create a resource group
    azure.azcollection.azure_rm_resourcegroup:
      name: "{{ RGName }}"
      location: eastus
      
  - name: Create storage account
    azure.azcollection.azure_rm_storageaccount:
      resource_group: "{{ RGName }}"
      name: httestaccount1234
      account_type: Standard_LRS
    
  - name: Create virtual network
    azure.azcollection.azure_rm_virtualnetwork:
      resource_group: "{{ RGName }}"
      name: testvn001
      address_prefixes: "10.10.0.0/16"
    
  - name: Add subnet
    azure.azcollection.azure_rm_subnet:
      resource_group: "{{ RGName }}"
      name: subnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: testvn001
    
  - name: Create public ip
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: "{{ RGName }}"
      allocation_method: Static
      name: publicip001
  
  - name: Create security group that allows SSH
    azure.azcollection.azure_rm_securitygroup:
      resource_group: "{{ RGName }}"
      name: secgroup001
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
          
  - name: Create NIC
    azure.azcollection.azure_rm_networkinterface:
      resource_group: "{{ RGName }}"
      name: testnic001
      virtual_network: testvn001
      subnet: subnet001
      public_ip_name: publicip001
      security_group: secgroup001
  
  - name: Create virtual machine
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: "{{ RGName }}"
      name: testvm001
      vm_size: Standard_B1s
      storage_account: httestaccount1234
      storage_container: testvm001
      storage_blob: testvm001.vhd
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      network_interfaces: testnic001
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
        
#OpenLogic:CentOS:7.5:latest
#MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest